namespace kinc_beef.Enums
{
	public enum VertexData : int32
	{
		KINC_G4_VERTEX_DATA_NONE,
		KINC_G4_VERTEX_DATA_FLOAT1,
		KINC_G4_VERTEX_DATA_FLOAT2,
		KINC_G4_VERTEX_DATA_FLOAT3,
		KINC_G4_VERTEX_DATA_FLOAT4,
		KINC_G4_VERTEX_DATA_FLOAT4X4,
		KINC_G4_VERTEX_DATA_SHORT2_NORM,
		KINC_G4_VERTEX_DATA_SHORT4_NORM,
		KINC_G4_VERTEX_DATA_COLOR
	}
}
